import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'

function run(cmd, cwd = process.cwd()) {
  try {
    return execSync(cmd, { cwd, encoding: 'utf-8', stdio: 'pipe' }).trim()
  } catch (error) {
    if (error.stdout) console.log(error.stdout.toString())
    if (error.stderr) console.error(error.stderr.toString())
    throw error
  }
}

export function isGitInitialized() {
  return fs.existsSync(path.join(process.cwd(), '.git'))
}

export function initGit() {
  run('git init -b main')
  // Initial commit to avoid issues with branch creation
  fs.writeFileSync('.gitignore', 'node_modules/\n.env\n.flux/\nworktrees/\n')
  run('git add .gitignore')
  run('git commit -m "flux: Initial commit"')
}

export function getBaseBranch() {
  try {
    // Try to get default branch from origin
    const remoteHead = run('git rev-parse --abbrev-ref origin/HEAD');
    if (remoteHead) {
      return remoteHead.split('/')[1];
    }
  } catch (e) {}
  
  // Fallback to checking if main or master exist
  try {
    const branches = run('git branch --format="%(refname:short)"').split('\n');
    if (branches.includes('main')) return 'main';
    if (branches.includes('master')) return 'master';
  } catch(e) {}
  
  return 'main';
}

export function createBranch(branchName) {
  run(`git checkout -b ${branchName}`)
}

export function checkoutBaseAndCreateBranch(branchName) {
  const baseBranch = getBaseBranch();
  
  // Auto-commit any pending workspace changes so they don't block branch switching or bleed
  try {
    const statusOut = run('git status --short');
    if (statusOut) {
      console.log('Auto-committing pending workspace changes...');
      run('git add .');
      run('git commit -m "flux: auto-commit pending changes before shadow creation"');
    }
  } catch (e) {
    console.error('Failed to auto-commit pending changes:', e);
  }

  try {
    run(`git checkout ${baseBranch}`);
  } catch (e) {
    console.log(`Could not checkout base branch ${baseBranch}, branching from current spot.`);
  }
  run(`git checkout -b ${branchName}`);
}

export function createShadowWorktree(branchName, shadowPath) {
  const baseBranch = getBaseBranch();
  run(`git worktree add -b ${branchName} ${shadowPath} ${baseBranch}`);
}

export function commitAll(message, cwd = process.cwd()) {
  try {
    run('git add .', cwd);
    // Escape double quotes for the commit message
    run(`git commit -m "${message.replace(/"/g, '\\"')}"`, cwd);
  } catch(e) {
    console.error('Failed to commit changes:', e.message);
  }
}

export function getDiff() {
  // Stage intent-to-add for untracked files so the AI can review new files
  try {
    run('git add -N .')
  } catch (e) {}

  // Get staged and unstaged changes, explicitly excluding .flux directory
  // We prefer unstaged or all changes against HEAD
  try {
    return run('git diff HEAD -- ":(exclude).flux"')
  } catch (e) {
    // maybe no HEAD yet, just git diff
    return run('git diff -- ":(exclude).flux"')
  }
}

export function status() {
  return run('git status --short')
}

export function createPullRequest(branchName, title, cwd = process.cwd()) {
  try {
    console.log(`Pushing branch ${branchName} to origin...`)
    run(`git push -u origin ${branchName}`, cwd)
    
    try {
      const existingPrs = run(`gh pr list --head ${branchName} --json url`, cwd);
      if (existingPrs && JSON.parse(existingPrs).length > 0) {
        console.log(`A Pull Request already exists for branch '${branchName}'. Skipping creation.`);
        return;
      }
    } catch (e) {
      // Ignore and proceed to create if list fails
    }

    console.log('Creating Pull Request...')
    run(`gh pr create --title "${title.replace(/"/g, '\\"')}" --body "Automated PR generated by flux agentic VCS for intent: ${title}"`, cwd)
    console.log('Successfully created PR!')
  } catch (e) {
    console.log('Note: Could not automatically create PR. Ensure `gh` CLI is installed/authenticated and this repo has an `origin` remote.')
  }
}
