import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import pc from 'picocolors'

function run(cmd, cwd = process.cwd()) {
  try {
    return execSync(cmd, { cwd, encoding: 'utf-8', stdio: 'pipe' }).trim()
  } catch (error) {
    if (error.stdout) console.log(error.stdout.toString())
    if (error.stderr) console.error(error.stderr.toString())
    throw error
  }
}

export function isGitInitialized() {
  return fs.existsSync(path.join(process.cwd(), '.git'))
}

export function initGit() {
  run('git init -b main')
  // Initial commit to avoid issues with branch creation
  fs.writeFileSync('.gitignore', 'node_modules/\n.env\n.flux/\nworktrees/\n')
  run('git add .gitignore')
  run('git commit -m "flux: Initial commit"')
}

export function getBaseBranch(cwd = process.cwd()) {
  try {
    // Try to get default branch from origin
    const remoteHead = run('git rev-parse --abbrev-ref origin/HEAD', cwd)
    if (remoteHead) {
      return remoteHead.split('/')[1]
    }
  } catch (e) {}

  // Fallback to checking if main or master exist
  try {
    const branches = run('git branch --format="%(refname:short)"', cwd).split('\n')
    if (branches.includes('main')) return 'main'
    if (branches.includes('master')) return 'master'
  } catch (e) {}

  return 'main'
}

export function getCurrentBranch(cwd = process.cwd()) {
  try {
    return run('git branch --show-current', cwd)
  } catch (e) {
    return ''
  }
}

export function createBranch(branchName) {
  run(`git checkout -b ${branchName}`)
}

export function checkoutBaseAndCreateBranch(branchName) {
  const baseBranch = getBaseBranch()

  // Auto-commit any pending workspace changes so they don't block branch switching or bleed
  try {
    const statusOut = run('git status --short')
    if (statusOut) {
      console.log(pc.yellow('⏳ Auto-committing pending workspace changes...'))
      run('git add .')
      run('git commit -m "flux: auto-commit pending changes before shadow creation"')
    }
  } catch (e) {
    console.error(pc.red('❌ Failed to auto-commit pending changes:'), e)
  }

  try {
    run(`git checkout ${baseBranch}`)
  } catch (e) {
    console.log(pc.yellow(`⚠️ Could not checkout base branch ${baseBranch}, branching from current spot.`))
  }
  run(`git checkout -b ${branchName}`)
}

export function createShadowWorktree(branchName, shadowPath) {
  const baseBranch = getBaseBranch()
  console.log(pc.gray(`Using base branch: ${baseBranch}`))
  console.log(pc.gray(`Creating shadow worktree: ${branchName} ${shadowPath}`))
  run(`git worktree add -b ${branchName} ${shadowPath}`)
}

export function commitAll(message, cwd = process.cwd()) {
  try {
    run('git add .', cwd)
    // Escape double quotes for the commit message
    run(`git commit -m "${message.replace(/"/g, '\\"')}"`, cwd)
  } catch (e) {
    console.error(pc.red('❌ Failed to commit changes:'), e.message)
  }
}

export function getDiff(cwd = process.cwd()) {
  // Stage intent-to-add for untracked files so the AI can review new files
  try {
    run('git add -N .', cwd)
  } catch (e) {}

  const baseBranch = getBaseBranch(cwd)
  console.log(pc.gray(`Using base branch: ${baseBranch}`))

  // Compare against base branch to show all changes made in this branch/worktree
  try {
    return run(`git diff ${baseBranch} -- ":(exclude).flux"`, cwd)
  } catch (e) {
    // Fallback to diffing against HEAD or working tree
    try {
      return run('git diff HEAD -- ":(exclude).flux"', cwd)
    } catch (e2) {
      return run('git diff -- ":(exclude).flux"', cwd)
    }
  }
}

export function status(cwd = process.cwd()) {
  return run('git status --short', cwd)
}

export function createPullRequest(branchName, title, cwd = process.cwd()) {
  try {
    console.log(pc.magenta(`📤 Pushing branch ${branchName} to origin...`))
    run(`git push -u origin ${branchName}`, cwd)

    try {
      const existingPrs = run(`gh pr list --head ${branchName} --json url`, cwd)
      if (existingPrs && JSON.parse(existingPrs).length > 0) {
        const prUrl = JSON.parse(existingPrs)[0].url
        console.log(pc.blue(`ℹ️ A Pull Request already exists for branch '${branchName}'. Skipping creation.`))
        console.log(pc.cyan(`🔗 PR Link: ${pc.underline(prUrl)}`))
        return
      }
    } catch (e) {
      // Ignore and proceed to create if list fails
    }

    console.log(pc.magenta('🔗 Creating Pull Request...'))
    const prUrl = run(
      `gh pr create --title "${title.replace(/"/g, '\\"')}" --body "Automated PR generated by flux agentic VCS for intent: ${title}"`,
      cwd,
    )
    console.log(pc.green('✅ Successfully created PR!'))
    if (prUrl) {
      console.log(pc.cyan(`🔗 PR Link: ${pc.underline(prUrl)}`))
    }
  } catch (e) {
    console.log(
      pc.yellow(
        '⚠️ Note: Could not automatically create PR. Ensure `gh` CLI is installed/authenticated and this repo has an `origin` remote.',
        e,
      ),
    )
    throw e
  }
}

export function mergePullRequest(branchName, cwd = process.cwd()) {
  try {
    console.log(pc.magenta(`🔀 Merging Pull Request for branch ${branchName}...`))
    run(`gh pr merge ${branchName} --squash --delete-branch`, cwd)
    console.log(pc.green('✅ Successfully merged Pull Request!'))
  } catch (e) {
    console.error(pc.red('❌ Failed to merge PR. Ensure there are no conflicts and `gh` is authenticated.'), e)
    throw e
  }
}

export function removeWorktree(shadowPath, cwd = process.cwd()) {
  try {
    console.log(pc.gray(`🧹 Cleaning up shadow worktree...`))
    run(`git worktree remove --force ${shadowPath}`, cwd)
  } catch (e) {
    console.error(pc.yellow(`⚠️ Could not automatically remove worktree at ${shadowPath}.`), e)
  }
}

export function pullBase(cwd = process.cwd()) {
  try {
    const baseBranch = getBaseBranch(cwd)
    console.log(pc.cyan(`📥 Pulling latest changes for ${baseBranch} in root workspace...`))
    run(`git checkout ${baseBranch}`, cwd)
    run('git pull', cwd)
    console.log(pc.green('✅ Root workspace synced successfully!'))
  } catch (e) {
    console.error(pc.red('❌ Failed to pull root workspace. You may have uncommitted changes.'), e)
  }
}
